# Generated by Django 2.1.3 on 2018-11-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
