# Generated by Django 2.1.3 on 2018-11-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20181123_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
